#!/usr/bin/env python3
# taken from: https://forum.freecadweb.org/viewtopic.php?t=41277
import sys
sys.path.append("/usr/lib/freecad/lib")
import FreeCAD
import Part
s = Part.Shape()
s.read(sys.argv[1])
s.exportStl(sys.argv[2], 2.5)
